
package org.itson.proyecto01.presentacion;

import java.awt.Color;

/**
 *
 * @author joset
 */
public class ConfirmarTransferenciaForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarTransferenciaForm
     */
    public ConfirmarTransferenciaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenuBar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnVerCuentas = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        panCuentaOrigenConfirmarTransferencia = new javax.swing.JPanel();
        lblCuentaOrigen1 = new javax.swing.JLabel();
        lblEstadoCuentaOrigen = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        panCuentaDestinoConfirmarTransferencia = new javax.swing.JPanel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblSaldoCuentaOrigen1 = new javax.swing.JLabel();
        txtNumeroCuentaDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panMontoTransferenciaConfirmarTransferencia = new javax.swing.JPanel();
        lblCuentaDestino1 = new javax.swing.JLabel();
        lblSaldoCuentaOrigen2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnConfirmarTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panMenuBar.setBackground(new java.awt.Color(12, 140, 233));

        btnUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");

        btnVerCuentas.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnVerCuentas.setText("Ver Cuentas");
        btnVerCuentas.setToolTipText("");
        btnVerCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuentasActionPerformed(evt);
            }
        });

        btnTransferir.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        btnRetiroSinCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRetiroSinCuenta.setText("<html>Retiro sin<br>cuenta</html> ");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        btnConsultarOperaciones.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConsultarOperaciones.setText("<html>Consultar<br>Operaciones</html>\n");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout panMenuBarLayout = new javax.swing.GroupLayout(panMenuBar);
        panMenuBar.setLayout(panMenuBarLayout);
        panMenuBarLayout.setHorizontalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarOperaciones)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetiroSinCuenta))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panMenuBarLayout.setVerticalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnVerCuentas)
                .addGap(18, 18, 18)
                .addComponent(btnTransferir)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panCuentaOrigenConfirmarTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panCuentaOrigenConfirmarTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaOrigen1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaOrigen1.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaOrigen1.setText("CUENTA ORIGEN");

        lblEstadoCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoCuentaOrigen.setText("Estado : Activa");

        lblSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible.setText("saldo");

        txtNumeroCuenta.setToolTipText("");

        javax.swing.GroupLayout panCuentaOrigenConfirmarTransferenciaLayout = new javax.swing.GroupLayout(panCuentaOrigenConfirmarTransferencia);
        panCuentaOrigenConfirmarTransferencia.setLayout(panCuentaOrigenConfirmarTransferenciaLayout);
        panCuentaOrigenConfirmarTransferenciaLayout.setHorizontalGroup(
            panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblCuentaOrigen1))
                    .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addComponent(lblEstadoCuentaOrigen)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addGap(158, 158, 158))))
        );
        panCuentaOrigenConfirmarTransferenciaLayout.setVerticalGroup(
            panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstadoCuentaOrigen)
                        .addGap(4, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCuentaOrigen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSaldoDisponible)
                .addGap(32, 32, 32))
        );

        panCuentaDestinoConfirmarTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panCuentaDestinoConfirmarTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaDestino.setText("CUENTA DESTINO");

        lblSaldoCuentaOrigen1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoCuentaOrigen1.setForeground(new java.awt.Color(255, 255, 255));

        txtNumeroCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaDestinoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("destinatario");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout panCuentaDestinoConfirmarTransferenciaLayout = new javax.swing.GroupLayout(panCuentaDestinoConfirmarTransferencia);
        panCuentaDestinoConfirmarTransferencia.setLayout(panCuentaDestinoConfirmarTransferenciaLayout);
        panCuentaDestinoConfirmarTransferenciaLayout.setHorizontalGroup(
            panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuentaDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(lblSaldoCuentaOrigen1)
                .addGap(64, 64, 64))
        );
        panCuentaDestinoConfirmarTransferenciaLayout.setVerticalGroup(
            panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblSaldoCuentaOrigen1))
                    .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblCuentaDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panMontoTransferenciaConfirmarTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panMontoTransferenciaConfirmarTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaDestino1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaDestino1.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaDestino1.setText("Monto");

        lblSaldoCuentaOrigen2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoCuentaOrigen2.setForeground(new java.awt.Color(255, 255, 255));

        txtMonto.setToolTipText("");
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMontoTransferenciaConfirmarTransferenciaLayout = new javax.swing.GroupLayout(panMontoTransferenciaConfirmarTransferencia);
        panMontoTransferenciaConfirmarTransferencia.setLayout(panMontoTransferenciaConfirmarTransferenciaLayout);
        panMontoTransferenciaConfirmarTransferenciaLayout.setHorizontalGroup(
            panMontoTransferenciaConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaConfirmarTransferenciaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblSaldoCuentaOrigen2)
                .addGap(64, 64, 64))
            .addGroup(panMontoTransferenciaConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCuentaDestino1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMontoTransferenciaConfirmarTransferenciaLayout.setVerticalGroup(
            panMontoTransferenciaConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCuentaDestino1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoCuentaOrigen2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmarTransferencia.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConfirmarTransferencia.setText("Confirmar Transferencia");
        btnConfirmarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panCuentaDestinoConfirmarTransferencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panCuentaOrigenConfirmarTransferencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panMontoTransferenciaConfirmarTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnConfirmarTransferencia)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panCuentaOrigenConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panCuentaDestinoConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panMontoTransferenciaConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        panCuentaOrigenConfirmarTransferencia.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestinoConfirmarTransferencia.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestinoConfirmarTransferencia.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerCuentasActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    private void txtNumeroCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaDestinoActionPerformed

    private void txtMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusGained
        if(txtMonto.getText().equals("Monto                                                                                                                                                                                                              $")){
            txtMonto.setText("");
            txtMonto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtMontoFocusGained

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        if(txtMonto.getText().isEmpty()){
            txtMonto.setText("Monto                                                                                                                                                                                                              $");
            txtMonto.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtMontoFocusLost

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnConfirmarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarTransferenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfirmarTransferencia;
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVerCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaDestino1;
    private javax.swing.JLabel lblCuentaOrigen1;
    private javax.swing.JLabel lblEstadoCuentaOrigen;
    private javax.swing.JLabel lblSaldoCuentaOrigen1;
    private javax.swing.JLabel lblSaldoCuentaOrigen2;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JPanel panCuentaDestinoConfirmarTransferencia;
    private javax.swing.JPanel panCuentaOrigenConfirmarTransferencia;
    private javax.swing.JPanel panMenuBar;
    private javax.swing.JPanel panMontoTransferenciaConfirmarTransferencia;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroCuentaDestino;
    // End of variables declaration//GEN-END:variables
}
