
package org.itson.proyecto01.presentacion;

import java.awt.Color;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import org.itson.proyecto01.dtos.NuevaTransferenciaDTO;
import org.itson.proyecto01.enums.TipoOperacion;
import org.itson.proyecto01.negocio.ITransferenciasBO;
import org.itson.proyecto01.negocio.NegocioException;

/**
 *
 * @author joset
 */
public class ConfirmarTransferenciaForm extends javax.swing.JFrame {
    private String cuentaSeleccionada;
    private String numeroDestino;
    private double monto;
    private LocalDateTime fechaHoraOperacion;
    private final ITransferenciasBO transferenciasBO;
    private String nombreCuentaDestino;
    /**
     * Creates new form ConfirmarTransferenciaForm
     */
    public ConfirmarTransferenciaForm(String cuentaSeleccionada, String numeroDestino, double monto,String nombreCuentaDestino,ITransferenciasBO transferenciasBO) {
        this.transferenciasBO = transferenciasBO;
        initComponents();
        
        btnConfirmarTransferencia.setBackground(Color.WHITE);
        btnConfirmarTransferencia.setForeground(Color.BLACK);
        btnConfirmarTransferencia.setFocusPainted(false);
        btnConfirmarTransferencia.setBorder(new javax.swing.border.LineBorder(new Color(12,140,233), 6, true));
        txtMonto.setEditable(false);
        txtNumeroCuenta.setEditable(false);
        txtNumeroCuentaDestino.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCuentaOrigenConfirmarTransferencia = new javax.swing.JPanel();
        lblCuentaOrigen1 = new javax.swing.JLabel();
        lblEstadoCuentaOrigen = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        panCuentaDestinoConfirmarTransferencia = new javax.swing.JPanel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblSaldoCuentaOrigen1 = new javax.swing.JLabel();
        txtNumeroCuentaDestino = new javax.swing.JTextField();
        lblNombredestinatario = new javax.swing.JLabel();
        panMontoTransferenciaConfirmarTransferencia = new javax.swing.JPanel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnConfirmarTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCuentaOrigenConfirmarTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panCuentaOrigenConfirmarTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaOrigen1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaOrigen1.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaOrigen1.setText("CUENTA ORIGEN");

        lblEstadoCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoCuentaOrigen.setText("Estado : Activa");

        lblSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible.setText("saldo");

        txtNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNumeroCuenta.setToolTipText("");

        javax.swing.GroupLayout panCuentaOrigenConfirmarTransferenciaLayout = new javax.swing.GroupLayout(panCuentaOrigenConfirmarTransferencia);
        panCuentaOrigenConfirmarTransferencia.setLayout(panCuentaOrigenConfirmarTransferenciaLayout);
        panCuentaOrigenConfirmarTransferenciaLayout.setHorizontalGroup(
            panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblCuentaOrigen1))
                    .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addComponent(lblEstadoCuentaOrigen)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addGap(158, 158, 158))))
        );
        panCuentaOrigenConfirmarTransferenciaLayout.setVerticalGroup(
            panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstadoCuentaOrigen)
                        .addGap(4, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCuentaOrigen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSaldoDisponible)
                .addGap(32, 32, 32))
        );

        panCuentaDestinoConfirmarTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panCuentaDestinoConfirmarTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaDestino.setText("CUENTA DESTINO");

        lblSaldoCuentaOrigen1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoCuentaOrigen1.setForeground(new java.awt.Color(255, 255, 255));

        txtNumeroCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNumeroCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaDestinoActionPerformed(evt);
            }
        });

        lblNombredestinatario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombredestinatario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombredestinatario.setText("destinatario");
        lblNombredestinatario.setToolTipText("");

        javax.swing.GroupLayout panCuentaDestinoConfirmarTransferenciaLayout = new javax.swing.GroupLayout(panCuentaDestinoConfirmarTransferencia);
        panCuentaDestinoConfirmarTransferencia.setLayout(panCuentaDestinoConfirmarTransferenciaLayout);
        panCuentaDestinoConfirmarTransferenciaLayout.setHorizontalGroup(
            panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuentaDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(lblNombredestinatario)
                .addGap(56, 56, 56)
                .addComponent(lblSaldoCuentaOrigen1)
                .addGap(64, 64, 64))
        );
        panCuentaDestinoConfirmarTransferenciaLayout.setVerticalGroup(
            panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblSaldoCuentaOrigen1))
                    .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblCuentaDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCuentaDestinoConfirmarTransferenciaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblNombredestinatario)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panMontoTransferenciaConfirmarTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panMontoTransferenciaConfirmarTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblMonto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("Monto");

        txtMonto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMonto.setToolTipText("");
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMontoTransferenciaConfirmarTransferenciaLayout = new javax.swing.GroupLayout(panMontoTransferenciaConfirmarTransferencia);
        panMontoTransferenciaConfirmarTransferencia.setLayout(panMontoTransferenciaConfirmarTransferenciaLayout);
        panMontoTransferenciaConfirmarTransferenciaLayout.setHorizontalGroup(
            panMontoTransferenciaConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaConfirmarTransferenciaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(panMontoTransferenciaConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMonto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMontoTransferenciaConfirmarTransferenciaLayout.setVerticalGroup(
            panMontoTransferenciaConfirmarTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaConfirmarTransferenciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnConfirmarTransferencia.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConfirmarTransferencia.setText("Confirmar Transferencia");
        btnConfirmarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panCuentaDestinoConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panCuentaOrigenConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panMontoTransferenciaConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnConfirmarTransferencia)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(panCuentaOrigenConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panCuentaDestinoConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panMontoTransferenciaConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        panCuentaOrigenConfirmarTransferencia.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestinoConfirmarTransferencia.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestinoConfirmarTransferencia.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaDestinoActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
       
        
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnConfirmarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTransferenciaActionPerformed
        try{
            fechaHoraOperacion = LocalDateTime.now();
            NuevaTransferenciaDTO nuevaTransferencia = new NuevaTransferenciaDTO(fechaHoraOperacion, TipoOperacion.TRANSFERENCIA, cuentaSeleccionada, numeroDestino, monto);
            this.transferenciasBO.crearNuevaTransferencia(nuevaTransferencia);
            JOptionPane.showMessageDialog(this, "Transferencia Realizada ", "informacion: ", JOptionPane.INFORMATION_MESSAGE);
            
            TransferenciaExitosaForm transferenciaExitosaForm = new TransferenciaExitosaForm(fechaHoraOperacion, cuentaSeleccionada, numeroDestino, monto,nombreCuentaDestino);
            transferenciaExitosaForm.setLocationRelativeTo(null);
            transferenciaExitosaForm.setVisible(true);

            this.dispose(); // cerrar ventana actual
        }catch(NegocioException ex){
            
        }
    }//GEN-LAST:event_btnConfirmarTransferenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarTransferencia;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen1;
    private javax.swing.JLabel lblEstadoCuentaOrigen;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombredestinatario;
    private javax.swing.JLabel lblSaldoCuentaOrigen1;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JPanel panCuentaDestinoConfirmarTransferencia;
    private javax.swing.JPanel panCuentaOrigenConfirmarTransferencia;
    private javax.swing.JPanel panMontoTransferenciaConfirmarTransferencia;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroCuentaDestino;
    // End of variables declaration//GEN-END:variables
}
