/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.proyecto01.presentacion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import org.itson.proyecto01.control.OperacionControl;
import org.itson.proyecto01.control.SesionControl;
/**
 *
 * @author Jesus Omar
 */
public class ConsultarOperacionesForm extends javax.swing.JFrame {

    private OperacionControl operacionControl;
    /**
     * Creates new form ConsultarOperacionesForm
     */
    public ConsultarOperacionesForm() {
        initComponents();
        Integer idCliente = SesionControl.getSesion().getCliente().getId();
        this.operacionControl = new OperacionControl(this);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logoBanco.jpg"));
        setIconImage(icon);
        utileriasBoton(btnUsuario);
        utileriasBoton(btnCerrarSesion);
        utileriasBoton(btnRealizarTransferencia);
        utileriasBoton(btnRetiroSinCuenta1);
        utileriasBoton(btnVerCuentas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenuBar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnVerCuentas = new javax.swing.JButton();
        btnRealizarTransferencia = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnRetiroSinCuenta1 = new javax.swing.JButton();
        lblTituloOperaciones = new javax.swing.JLabel();
        lblFiltro = new javax.swing.JLabel();
        lblTipoOperacion = new javax.swing.JLabel();
        TipoOperacionComboBox = new javax.swing.JComboBox<>();
        rangoFechasComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOperaciones = new javax.swing.JTable();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial de Operaciones");

        panMenuBar.setBackground(new java.awt.Color(45, 102, 237));

        btnUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");

        btnVerCuentas.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnVerCuentas.setText("Menu Principal");
        btnVerCuentas.setToolTipText("");

        btnRealizarTransferencia.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRealizarTransferencia.setText("<html>Realizar<br>Transferencia</html> ");

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        btnRetiroSinCuenta1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRetiroSinCuenta1.setText("<html>Realizar <br>Retiro</html> ");
        btnRetiroSinCuenta1.setToolTipText("");
        btnRetiroSinCuenta1.setActionCommand("  ");

        javax.swing.GroupLayout panMenuBarLayout = new javax.swing.GroupLayout(panMenuBar);
        panMenuBar.setLayout(panMenuBarLayout);
        panMenuBarLayout.setHorizontalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRetiroSinCuenta1)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCuentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRealizarTransferencia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panMenuBarLayout.setVerticalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addGap(26, 26, 26)
                .addComponent(btnVerCuentas)
                .addGap(32, 32, 32)
                .addComponent(btnRealizarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCerrarSesion)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        lblTituloOperaciones.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloOperaciones.setForeground(new java.awt.Color(45, 102, 237));
        lblTituloOperaciones.setText("Operaciones");

        lblFiltro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFiltro.setText("Filtro:");

        lblTipoOperacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoOperacion.setText("Tipo de operacion");

        tablaOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Fecha y hora", "Monto", "Numero de cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaOperaciones);
        if (tablaOperaciones.getColumnModel().getColumnCount() > 0) {
            tablaOperaciones.getColumnModel().getColumn(0).setResizable(false);
            tablaOperaciones.getColumnModel().getColumn(1).setResizable(false);
            tablaOperaciones.getColumnModel().getColumn(3).setResizable(false);
        }

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFiltro)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTipoOperacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TipoOperacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFecha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rangoFechasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(lblTituloOperaciones)))
                .addGap(0, 60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTituloOperaciones)
                .addGap(30, 30, 30)
                .addComponent(lblFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoOperacion)
                    .addComponent(TipoOperacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangoFechasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void utileriasBoton(JButton btn) {
        btn.setBackground(Color.WHITE);
        btn.setOpaque(true);
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(true);
        btn.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1, true));
    }

    public JComboBox<String> getTipoOperacionComboBox() {
        return TipoOperacionComboBox;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnRealizarTransferencia() {
        return btnRealizarTransferencia;
    }

    public JButton getBtnRetiroSinCuenta1() {
        return btnRetiroSinCuenta1;
    }

    public JButton getBtnUsuario() {
        return btnUsuario;
    }

    public JButton getBtnVerCuentas() {
        return btnVerCuentas;
    }

    public JComboBox<String> getRangoFechasComboBox() {
        return rangoFechasComboBox;
    }

    public JTable getTablaOperaciones() {
        return tablaOperaciones;
    }
    
    public void setModelTipoOperacion(DefaultComboBoxModel<String> modelo){
        this.TipoOperacionComboBox.setModel(modelo);
    }
    
    public void setModelRangoFechas(DefaultComboBoxModel<String> modeloFechas){
        this.rangoFechasComboBox.setModel(modeloFechas);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TipoOperacionComboBox;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnRealizarTransferencia;
    private javax.swing.JButton btnRetiroSinCuenta1;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVerCuentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JLabel lblTituloOperaciones;
    private javax.swing.JPanel panMenuBar;
    private javax.swing.JComboBox<String> rangoFechasComboBox;
    private javax.swing.JTable tablaOperaciones;
    // End of variables declaration//GEN-END:variables
}
