/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.proyecto01.presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.itson.proyecto01.control.MenuControl;
import org.itson.proyecto01.enums.EstadoCuenta;

/**
 *
 * @author joset
 */
    public class MenuPrincipalForm extends javax.swing.JFrame {

        private final JPanel contenedorCuentas;
        private final JScrollPane scrollCuentas;
        private final MenuControl menuControl;

        /**
         * Creates new form menuPrincipal
         */
        public MenuPrincipalForm(int idCliente) {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logoBanco.jpg"));
        setIconImage(icon);
        menuControl = new MenuControl(this, idCliente);

        // Panel que contendrá las cuentas
        contenedorCuentas = new JPanel();
        contenedorCuentas.setLayout(new BoxLayout(contenedorCuentas, BoxLayout.Y_AXIS));
        contenedorCuentas.setBackground(new Color(245, 247, 250));

        // Scroll de las cuentas
        scrollCuentas = new JScrollPane(contenedorCuentas);
        scrollCuentas.setBorder(null);
        scrollCuentas.getVerticalScrollBar().setUnitIncrement(16);

        // panel central que tiene el scroll y el label de bienvenida
        JPanel panelCentral = new JPanel();
        panelCentral.setLayout(new BoxLayout(panelCentral, BoxLayout.Y_AXIS));
        panelCentral.setBackground(Color.WHITE);

        panelCentral.add(lblBienvenido);
        panelCentral.add(Box.createVerticalStrut(10)); // espacio
        panelCentral.add(scrollCuentas);
        panelCentral.add(Box.createVerticalStrut(10));
        panelCentral.add(btnAltaCuenta);

        // Agregar panelCentral al jPanel1
        panCuentas.add(panelCentral, BorderLayout.CENTER);

        // Actualizar el panel principal
        panCuentas.revalidate();
        panCuentas.repaint();

        // Cargar cuentas desde el control
        menuControl.cargarCuentasCliente();
        
        // Cargar los estilos de los botones
        utileriasBoton(btnAltaCuenta);
        utileriasBoton(btnCancelarCuenta);
        utileriasBoton(btnCerrarSesion);
        utileriasBoton(btnConsultarOperaciones);
        utileriasBoton(btnMostrarTransferencias);
        utileriasBoton(btnUsuario);
        utileriasBoton(btnRetiroSinCuenta);
        
        
        panPieDePantalla.setLayout(new BoxLayout(panPieDePantalla, BoxLayout.X_AXIS));
        panPieDePantalla.add(Box.createHorizontalGlue());
        panPieDePantalla.add(btnCancelarCuenta);
        panPieDePantalla.add(Box.createHorizontalStrut(40)); // separación
        panPieDePantalla.add(btnAltaCuenta);
        panPieDePantalla.add(Box.createHorizontalGlue());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panMenuBar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnMostrarTransferencias = new javax.swing.JButton();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        panPieDePantalla = new javax.swing.JPanel();
        btnAltaCuenta = new javax.swing.JButton();
        btnCancelarCuenta = new javax.swing.JButton();
        panCuentas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1011, 705));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panMenuBar.setBackground(new java.awt.Color(45, 102, 237));

        btnUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnMostrarTransferencias.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnMostrarTransferencias.setText("<html>Realizar<br>Transferencias</html>\n");
        btnMostrarTransferencias.setToolTipText("");
        btnMostrarTransferencias.setActionCommand("  ");
        btnMostrarTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTransferenciasActionPerformed(evt);
            }
        });

        btnConsultarOperaciones.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConsultarOperaciones.setText("<html>Consultar<br>Operaciones</html>\n");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        btnRetiroSinCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRetiroSinCuenta.setText("<html>Retiro sin <br>Cuenta</html> ");
        btnRetiroSinCuenta.setToolTipText("");
        btnRetiroSinCuenta.setActionCommand("  ");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuBarLayout = new javax.swing.GroupLayout(panMenuBar);
        panMenuBar.setLayout(panMenuBarLayout);
        panMenuBarLayout.setHorizontalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMenuBarLayout.createSequentialGroup()
                        .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarTransferencias)
                            .addComponent(btnConsultarOperaciones)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnRetiroSinCuenta))
                .addContainerGap())
        );
        panMenuBarLayout.setVerticalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarTransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addGap(202, 202, 202))
        );

        jPanel1.add(panMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        panPieDePantalla.setBackground(new java.awt.Color(255, 255, 255));

        btnAltaCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        btnAltaCuenta.setForeground(new java.awt.Color(45, 102, 237));
        btnAltaCuenta.setText("Alta de Cuenta");
        btnAltaCuenta.setPreferredSize(new java.awt.Dimension(220, 45));
        btnAltaCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltaCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAltaCuentaMouseExited(evt);
            }
        });
        btnAltaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaCuentaActionPerformed(evt);
            }
        });

        btnCancelarCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 20)); // NOI18N
        btnCancelarCuenta.setForeground(new java.awt.Color(45, 102, 237));
        btnCancelarCuenta.setText("Cancelar Cuenta");
        btnCancelarCuenta.setPreferredSize(new java.awt.Dimension(220, 45));
        btnCancelarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarCuentaMouseExited(evt);
            }
        });
        btnCancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPieDePantallaLayout = new javax.swing.GroupLayout(panPieDePantalla);
        panPieDePantalla.setLayout(panPieDePantallaLayout);
        panPieDePantallaLayout.setHorizontalGroup(
            panPieDePantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPieDePantallaLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnCancelarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnAltaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        panPieDePantallaLayout.setVerticalGroup(
            panPieDePantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPieDePantallaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panPieDePantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(panPieDePantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 618, 730, 90));

        panCuentas.setBackground(new java.awt.Color(255, 255, 255));
        panCuentas.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 60, 720, 552));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(45, 102, 237));
        lblBienvenido.setText("<html><center>!Bienvenido!</center></html>");
        jPanel2.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel crearPanelCuenta(String numeroCuenta, EstadoCuenta estado, double saldo) {

        JPanel panCuenta = new JPanel(new BorderLayout());
        panCuenta.setBackground(new Color(45, 102, 237));
        panCuenta.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.WHITE, 6, true),
                BorderFactory.createEmptyBorder(12, 15, 12, 15)
        ));
        panCuenta.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));

        // Parte Superiro del panel
        JPanel panelTop = new JPanel(new BorderLayout());
        panelTop.setOpaque(false);

        JLabel lblTituloCuenta = new JLabel("CUENTA EN PESOS");
        lblTituloCuenta.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblTituloCuenta.setForeground(Color.WHITE);

        JLabel lblEstadoCuenta = new JLabel("Estado: " + estado);
        lblEstadoCuenta.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblEstadoCuenta.setForeground(Color.WHITE);

        panelTop.add(lblTituloCuenta, BorderLayout.WEST);
        panelTop.add(lblEstadoCuenta, BorderLayout.EAST);

        //Parte central del panel
        JPanel panelCentro = new JPanel(new BorderLayout());
        panelCentro.setOpaque(false);

        // parte Izq
        JPanel panelIzq = new JPanel();
        panelIzq.setOpaque(false);
        panelIzq.setLayout(new BoxLayout(panelIzq, BoxLayout.Y_AXIS));

        JLabel lblNumero = new JLabel("Número de cuenta");
        lblNumero.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblNumero.setForeground(new Color(220, 220, 220));

        JLabel lblNumeroCuenta = new JLabel(numeroCuenta);
        lblNumeroCuenta.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblNumeroCuenta.setForeground(Color.WHITE);

        panelIzq.add(lblNumero);
        panelIzq.add(lblNumeroCuenta);

        // parte Derecha
        JPanel panelDer = new JPanel();
        panelDer.setOpaque(false);
        panelDer.setLayout(new BoxLayout(panelDer, BoxLayout.Y_AXIS));

        JLabel lblSaldoDisponible = new JLabel(String.format("$%,.2f", saldo));
        lblSaldoDisponible.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblSaldoDisponible.setForeground(Color.WHITE);
        lblSaldoDisponible.setAlignmentX(JLabel.RIGHT_ALIGNMENT);

        JLabel lblSaldo = new JLabel("Saldo Disponible");
        lblSaldo.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        lblSaldo.setForeground(new Color(220, 220, 220));
        lblSaldo.setAlignmentX(JLabel.RIGHT_ALIGNMENT);

        panelDer.add(lblSaldoDisponible);
        panelDer.add(lblSaldo);

        panelCentro.add(panelIzq, BorderLayout.WEST);
        panelCentro.add(panelDer, BorderLayout.EAST);

        //juntar las partes
        panCuenta.add(panelTop, BorderLayout.NORTH);
        panCuenta.add(panelCentro, BorderLayout.CENTER);

        return panCuenta;
    }

    public void agregarPanelCuenta(String numeroCuenta, EstadoCuenta estado, double saldo) {
        JPanel panCuenta = crearPanelCuenta(numeroCuenta, estado, saldo);
        contenedorCuentas.add(panCuenta);
        contenedorCuentas.revalidate();
        contenedorCuentas.repaint();
    }
    private void utileriasBoton(JButton btn) {
        btn.setBackground(Color.WHITE);
        btn.setOpaque(true);
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(true);
        btn.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1, true));
    }

    private void btnMostrarTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTransferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarTransferenciasActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAltaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaCuentaActionPerformed

    }//GEN-LAST:event_btnAltaCuentaActionPerformed

    private void btnCancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCuentaActionPerformed

    private void btnAltaCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaCuentaMouseEntered
        btnAltaCuenta.setBackground(new Color(12,140,233));
    }//GEN-LAST:event_btnAltaCuentaMouseEntered

    private void btnAltaCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaCuentaMouseExited
        btnAltaCuenta.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnAltaCuentaMouseExited

    private void btnCancelarCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarCuentaMouseEntered
        btnCancelarCuenta.setBackground(new Color(12,140,233));
    }//GEN-LAST:event_btnCancelarCuentaMouseEntered

    private void btnCancelarCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarCuentaMouseExited
        btnCancelarCuenta.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnCancelarCuentaMouseExited

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed
    // Dentro de MenuPrincipalForm
    public JButton getBtnMostrarTransferencias() {
        return btnMostrarTransferencias;
    }

    public JButton getBtnMostrarRetiroSinCuenta() {
        return btnRetiroSinCuenta;
    }
    
    public JButton getBtnCancelarCuenta() {
        return btnCancelarCuenta;
    }
    
     public JButton getBtnAltaCuenta() {
        return btnAltaCuenta;
    }

    public JButton getBtnConsultarOperaciones() {
        return btnConsultarOperaciones;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnUsuario() {
        return btnUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaCuenta;
    private javax.swing.JButton btnCancelarCuenta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnMostrarTransferencias;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JPanel panCuentas;
    private javax.swing.JPanel panMenuBar;
    private javax.swing.JPanel panPieDePantalla;
    // End of variables declaration//GEN-END:variables
}
