/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.proyecto01.presentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.itson.proyecto01.control.MenuControl;
import org.itson.proyecto01.entidades.Cuenta;
import org.itson.proyecto01.enums.EstadoCuenta;
import org.itson.proyecto01.negocio.NegocioException;


/**
 *
 * @author joset
 */
public class MenuPrincipalForm extends javax.swing.JFrame {
    private int idCliente;
    private JPanel contenedorCuentas;
    private JScrollPane scrollCuentas;
    private MenuControl menuControl;
    /**
     * Creates new form menuPrincipal
     */
    public MenuPrincipalForm(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
        menuControl = new MenuControl(this,idCliente);
        // JPanel de las cuentas
        contenedorCuentas = new JPanel();
        contenedorCuentas.setLayout(new BoxLayout(contenedorCuentas, BoxLayout.Y_AXIS));
        contenedorCuentas.setBackground(new Color(245, 247, 250)); 

        scrollCuentas = new JScrollPane(contenedorCuentas);
        scrollCuentas.setBorder(null);
        scrollCuentas.setPreferredSize(new Dimension(700, 400));

        // Scroll del JpanelPrincipal por si hay muchas cuentas
        jPanel1.add(scrollCuentas);
        jPanel1.revalidate();
        jPanel1.repaint();
        menuControl.cargarCuentasCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panMenuBar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnMostrarTransferencias = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnContinuarTransferencia = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        panCuentaUsuario1 = new javax.swing.JPanel();
        lblNumeroCuenta1 = new javax.swing.JLabel();
        lblCuentaenPesos = new javax.swing.JLabel();
        lblEstadoCuenta1Usuario = new javax.swing.JLabel();
        lblSaldo1 = new javax.swing.JLabel();
        lblSaldoDisponible1 = new javax.swing.JLabel();
        lblNumeroCuenta1Usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panMenuBar.setBackground(new java.awt.Color(45, 102, 237));

        btnUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnMostrarTransferencias.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnMostrarTransferencias.setText("<html>Realizar<br>Transferencias</html>\n");
        btnMostrarTransferencias.setToolTipText("");
        btnMostrarTransferencias.setActionCommand("  ");
        btnMostrarTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTransferenciasActionPerformed(evt);
            }
        });

        btnRetiroSinCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRetiroSinCuenta.setText("<html>Retiro sin<br>cuenta</html> ");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        btnConsultarOperaciones.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConsultarOperaciones.setText("<html>Consultar<br>Operaciones</html>\n");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout panMenuBarLayout = new javax.swing.GroupLayout(panMenuBar);
        panMenuBar.setLayout(panMenuBarLayout);
        panMenuBarLayout.setHorizontalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarTransferencias)
                    .addComponent(btnConsultarOperaciones)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetiroSinCuenta))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panMenuBarLayout.setVerticalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarTransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addGap(137, 137, 137))
        );

        btnContinuarTransferencia.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnContinuarTransferencia.setText("Continuar");
        btnContinuarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarTransferenciaActionPerformed(evt);
            }
        });

        lblBienvenido.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        lblBienvenido.setText("!Bienvenido!");

        panCuentaUsuario1.setBackground(new java.awt.Color(45, 102, 237));
        panCuentaUsuario1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblNumeroCuenta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroCuenta1.setText("Numero de cuenta");

        lblCuentaenPesos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaenPesos.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaenPesos.setText("CUENTA EN PESOS");

        lblEstadoCuenta1Usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoCuenta1Usuario.setText("Estado : ");

        lblSaldo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSaldo1.setForeground(new java.awt.Color(204, 204, 204));
        lblSaldo1.setText("Saldo Disponible");

        lblSaldoDisponible1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoDisponible1.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible1.setText("0.00");

        lblNumeroCuenta1Usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroCuenta1Usuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroCuenta1Usuario.setText("Numero de cuenta");

        javax.swing.GroupLayout panCuentaUsuario1Layout = new javax.swing.GroupLayout(panCuentaUsuario1);
        panCuentaUsuario1.setLayout(panCuentaUsuario1Layout);
        panCuentaUsuario1Layout.setHorizontalGroup(
            panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaUsuario1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstadoCuenta1Usuario)
                .addContainerGap())
            .addGroup(panCuentaUsuario1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroCuenta1)
                    .addGroup(panCuentaUsuario1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNumeroCuenta1Usuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addGroup(panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaUsuario1Layout.createSequentialGroup()
                        .addComponent(lblSaldo1)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaUsuario1Layout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
            .addGroup(panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCuentaUsuario1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblCuentaenPesos)
                    .addContainerGap(605, Short.MAX_VALUE)))
        );
        panCuentaUsuario1Layout.setVerticalGroup(
            panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstadoCuenta1Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panCuentaUsuario1Layout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible1)
                        .addGap(4, 4, 4)
                        .addComponent(lblSaldo1))
                    .addGroup(panCuentaUsuario1Layout.createSequentialGroup()
                        .addComponent(lblNumeroCuenta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumeroCuenta1Usuario)
                        .addGap(6, 6, 6)))
                .addGap(30, 30, 30))
            .addGroup(panCuentaUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCuentaUsuario1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblCuentaenPesos)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(lblBienvenido)
                        .addGap(0, 372, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(btnContinuarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panCuentaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(56, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCuentaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(btnContinuarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(panMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panCuentaUsuario1.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public JPanel crearPanelCuenta( String numeroCuenta, EstadoCuenta estado, double saldo) {
        JPanel panCuenta = new JPanel();
        panCuenta.setBackground(new Color(45, 102, 237));
        panCuenta.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.WHITE, 6, true),
            BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));

        JLabel lblCuentaUsuario = new JLabel("CUENTA EN PESOS");
        lblCuentaUsuario.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblCuentaUsuario.setForeground(Color.WHITE); 

        JLabel lblNumeroCuenta = new JLabel("Número de cuenta");
        lblNumeroCuenta.setFont(new Font("Segoe UI", Font.BOLD, 12));
        JLabel lblNumeroCuentaUsuario = new JLabel(numeroCuenta);
        lblNumeroCuentaUsuario.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNumeroCuentaUsuario.setForeground(Color.WHITE);

        JLabel lblEstadoCuenta = new JLabel("Estado: " + estado);
        lblEstadoCuenta.setFont(new Font("Segoe UI", Font.BOLD, 12));

        JLabel lblSaldo = new JLabel("Saldo disponible");
        lblSaldo.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblSaldo.setForeground(new Color(204, 204, 204));

        JLabel lblSaldoDisponible = new JLabel(String.format("%.2f", saldo));
        lblSaldoDisponible.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblSaldoDisponible.setForeground(Color.WHITE);

        panCuenta.setLayout(new BoxLayout(panCuenta, BoxLayout.Y_AXIS));
        panCuenta.add(lblCuentaUsuario);
        panCuenta.add(Box.createVerticalStrut(10));
        panCuenta.add(lblNumeroCuenta);
        panCuenta.add(lblNumeroCuentaUsuario);
        panCuenta.add(Box.createVerticalStrut(5));
        panCuenta.add(lblEstadoCuenta);
        panCuenta.add(Box.createVerticalStrut(10));
        panCuenta.add(lblSaldoDisponible);
        panCuenta.add(lblSaldo);

        return panCuenta;
    }
    public void agregarPanelCuenta( String numeroCuenta, EstadoCuenta estado, double saldo) {
        JPanel panCuenta = crearPanelCuenta( numeroCuenta, estado, saldo);
        contenedorCuentas.add(panCuenta);
        contenedorCuentas.revalidate();
        contenedorCuentas.repaint();
    }
    
    private void btnMostrarTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTransferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarTransferenciasActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    private void btnContinuarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarTransferenciaActionPerformed
       
    }//GEN-LAST:event_btnContinuarTransferenciaActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed
    // Dentro de MenuPrincipalForm
    public JButton getBtnMostrarTransferencias() {
        return btnMostrarTransferencias;
    }

    public JButton getBtnRetiroSinCuenta() {
        return btnRetiroSinCuenta;
    }

    public JButton getBtnConsultarOperaciones() {
        return btnConsultarOperaciones;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnUsuario() {
        return btnUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnContinuarTransferencia;
    private javax.swing.JButton btnMostrarTransferencias;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCuentaenPesos;
    private javax.swing.JLabel lblEstadoCuenta1Usuario;
    private javax.swing.JLabel lblNumeroCuenta1;
    private javax.swing.JLabel lblNumeroCuenta1Usuario;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldoDisponible1;
    private javax.swing.JPanel panCuentaUsuario1;
    private javax.swing.JPanel panMenuBar;
    // End of variables declaration//GEN-END:variables
}
