/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.proyecto01.presentacion;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author joset
 */
public class RetiroSinCuentaForm extends javax.swing.JFrame {

    /**
     * Creates new form RetiroSinCuentaForm
     */
    public RetiroSinCuentaForm() {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logoBanco.jpg"));
        setIconImage(icon);
        utileriasBoton(btnRetirar);
        utileriasBoton(btnCancelarRetiro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        PanCentro = new javax.swing.JPanel();
        lblFolio = new javax.swing.JLabel();
        txtNumeroFolio = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblNombreCuenta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMontoRetiro = new javax.swing.JLabel();
        lblFechaExpiracion = new javax.swing.JLabel();
        lblFechaExpiracionRetiro = new javax.swing.JLabel();
        panPanelPie = new javax.swing.JPanel();
        btnCancelarRetiro = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retiro sin Cuenta");

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panTitulo.setBackground(new java.awt.Color(255, 255, 255));
        panTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(45, 102, 237));
        lblTitulo.setText("Retiro sin cuenta");
        panTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        PanCentro.setBackground(new java.awt.Color(255, 255, 255));
        PanCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFolio.setBackground(new java.awt.Color(255, 255, 255));
        lblFolio.setForeground(new java.awt.Color(153, 153, 153));
        lblFolio.setText("Folio: ");
        PanCentro.add(lblFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 61, -1, -1));

        txtNumeroFolio.setToolTipText("");
        txtNumeroFolio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFolioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFolioFocusLost(evt);
            }
        });
        txtNumeroFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFolioActionPerformed(evt);
            }
        });
        PanCentro.add(txtNumeroFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 83, 233, -1));

        lblContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        lblContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        lblContrasenia.setText("Contraseña:");
        PanCentro.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 123, -1, -1));

        txtContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseniaFocusLost(evt);
            }
        });
        PanCentro.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 145, 233, -1));

        lblNombre.setText("Nombre:");
        PanCentro.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        PanCentro.add(lblNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 20));

        jLabel3.setText("Monto: ");
        PanCentro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));
        PanCentro.add(lblMontoRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 180, 20));

        lblFechaExpiracion.setText("Expira:");
        PanCentro.add(lblFechaExpiracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 20));
        PanCentro.add(lblFechaExpiracionRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 180, 20));

        panPanelPie.setBackground(new java.awt.Color(255, 255, 255));
        panPanelPie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelarRetiro.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCancelarRetiro.setForeground(new java.awt.Color(45, 102, 237));
        btnCancelarRetiro.setText("Cancelar");
        btnCancelarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRetiroActionPerformed(evt);
            }
        });
        panPanelPie.add(btnCancelarRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 50));

        btnRetirar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(45, 102, 237));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        panPanelPie.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 50));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panPanelPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(panPanelPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void utileriasBoton(JButton btn) {
        btn.setBackground(Color.WHITE);
        btn.setOpaque(true);
        btn.setContentAreaFilled(true);
        btn.setBorder(new javax.swing.border.LineBorder(new Color(45,102,237), 2, true));
    }
    private void txtNumeroFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroFolioActionPerformed

    private void btnCancelarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRetiroActionPerformed

    }//GEN-LAST:event_btnCancelarRetiroActionPerformed

    private void txtNumeroFolioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFolioFocusGained
        if (txtNumeroFolio.getText().equals("Ingrese numero de Folio")) {
            txtNumeroFolio.setText("");
            txtNumeroFolio.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNumeroFolioFocusGained

    private void txtNumeroFolioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFolioFocusLost
        if (txtNumeroFolio.getText().equals("")) {
            txtNumeroFolio.setText("Ingrese numero de Folio");
            txtNumeroFolio.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtNumeroFolioFocusLost

    private void txtContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusGained
        if (txtContrasenia.getText().equals("Ingrese la contraseña")) {
            txtContrasenia.setText("");
            txtContrasenia.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtContraseniaFocusGained

    private void txtContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseniaFocusLost
        if (txtContrasenia.getText().equals("")) {
            txtContrasenia.setText("Ingrese la contraseña");
            txtContrasenia.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtContraseniaFocusLost

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarActionPerformed
    public JButton getBtnRetirar(){
        return btnRetirar;
    }
    public JButton getBtnCancelar(){
        return btnCancelarRetiro;
    }
    public JTextField getTxtContrasenia(){
        return txtContrasenia;
    }
    public JTextField getTxtFolio(){
        return txtNumeroFolio;
    }
    public JLabel getLblNombreCuenta(){
        return lblNombreCuenta;
    }
    public JLabel getLblMontoRetiro(){
        return lblMontoRetiro;
    }
     public JLabel getLblFechaExpiracion(){
        return lblFechaExpiracionRetiro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanCentro;
    private javax.swing.JButton btnCancelarRetiro;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblFechaExpiracion;
    private javax.swing.JLabel lblFechaExpiracionRetiro;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblMontoRetiro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panPanelPie;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtNumeroFolio;
    // End of variables declaration//GEN-END:variables
}
