
package org.itson.proyecto01.presentacion;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.itson.proyecto01.entidades.Cuenta;
import org.itson.proyecto01.negocio.ICuentasBO;
import org.itson.proyecto01.negocio.NegocioException;

/**
 *
 * @author joset
 */
public class TransferenciaForm extends javax.swing.JFrame {
    
    /**
     * Creates new form TransferenciaForm
     */
    ICuentasBO cuentasBO; 
    private Integer idCliente ;
    /**
     * el metodo constructivo inicializamos el id cliente ya que todavia 
     * @param cuentasBO 
     */
    public TransferenciaForm(ICuentasBO cuentasBO) {      
        this.cuentasBO = cuentasBO;
        initComponents();
        this.idCliente = 1; 
        this.cargarCuentasCliente();
        
        this.add(btnContinuarTransferencia);
        txtMonto.setText("Monto                                                                                                                                                                                                              $");
        txtMonto.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void cargarCuentasCliente() {
        try {
            List<Cuenta> listaCuentasCliente = this.cuentasBO.consultarCuentasCliente(idCliente);// id cliente es el id que el login va a mandar una vez que este creado 
            DefaultComboBoxModel<Cuenta> modeloComboBox = new DefaultComboBoxModel<>();
            
            for (Cuenta cuenta : listaCuentasCliente) {
                modeloComboBox.addElement(cuenta);
            }

            cboCuentasCliente.setModel(modeloComboBox);

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,"Error al consultar las cuentas", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenuBar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnVerCuentas = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblTrasnferirTitulo = new javax.swing.JLabel();
        panCuentaOrigen = new javax.swing.JPanel();
        lblNumeroCuentaOrigen = new javax.swing.JLabel();
        lblCuentaOrigen1 = new javax.swing.JLabel();
        cboCuentasCliente = new javax.swing.JComboBox<>();
        lblEstadoCuentaOrigen = new javax.swing.JLabel();
        lblSaldoCuentaOrigen = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        panCuentaDestino = new javax.swing.JPanel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblNumeroCuentaDestino = new javax.swing.JLabel();
        lblSaldoCuentaOrigen1 = new javax.swing.JLabel();
        txtNumeroCuentaDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panMontoTransferencia = new javax.swing.JPanel();
        lblCuentaDestino1 = new javax.swing.JLabel();
        lblSaldoCuentaOrigen2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnContinuarTransferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panMenuBar.setBackground(new java.awt.Color(12, 140, 233));

        btnUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");

        btnVerCuentas.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnVerCuentas.setText("Ver Cuentas");
        btnVerCuentas.setToolTipText("");
        btnVerCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuentasActionPerformed(evt);
            }
        });

        btnTransferir.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        btnRetiroSinCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRetiroSinCuenta.setText("<html>Retiro sin<br>cuenta</html> ");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        btnConsultarOperaciones.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConsultarOperaciones.setText("<html>Consultar<br>Operaciones</html>\n");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout panMenuBarLayout = new javax.swing.GroupLayout(panMenuBar);
        panMenuBar.setLayout(panMenuBarLayout);
        panMenuBarLayout.setHorizontalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarOperaciones)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetiroSinCuenta))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panMenuBarLayout.setVerticalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnVerCuentas)
                .addGap(18, 18, 18)
                .addComponent(btnTransferir)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTrasnferirTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        lblTrasnferirTitulo.setText("Transferir");

        panCuentaOrigen.setBackground(new java.awt.Color(12, 140, 233));
        panCuentaOrigen.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblNumeroCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroCuentaOrigen.setText("Numero de cuenta");

        lblCuentaOrigen1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaOrigen1.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaOrigen1.setText("CUENTA ORIGEN");

        cboCuentasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuentasClienteActionPerformed(evt);
            }
        });

        lblEstadoCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoCuentaOrigen.setText("Estado : Activa");

        lblSaldoCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSaldoCuentaOrigen.setForeground(new java.awt.Color(204, 204, 204));
        lblSaldoCuentaOrigen.setText("Saldo Disponible");

        lblSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible.setText("saldo");

        javax.swing.GroupLayout panCuentaOrigenLayout = new javax.swing.GroupLayout(panCuentaOrigen);
        panCuentaOrigen.setLayout(panCuentaOrigenLayout);
        panCuentaOrigenLayout.setHorizontalGroup(
            panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(cboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaldoCuentaOrigen)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstadoCuentaOrigen)
                .addGap(64, 64, 64))
            .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblNumeroCuentaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaldoDisponible)
                .addGap(132, 132, 132))
            .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblCuentaOrigen1)
                    .addContainerGap(585, Short.MAX_VALUE)))
        );
        panCuentaOrigenLayout.setVerticalGroup(
            panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstadoCuentaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblNumeroCuentaOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addGap(4, 4, 4)))
                .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoCuentaOrigen))
                .addGap(24, 24, 24))
            .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblCuentaOrigen1)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        panCuentaDestino.setBackground(new java.awt.Color(12, 140, 233));
        panCuentaDestino.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaDestino.setText("CUENTA DESTINO");

        lblNumeroCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroCuentaDestino.setText("Numero de cuenta");

        lblSaldoCuentaOrigen1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoCuentaOrigen1.setForeground(new java.awt.Color(255, 255, 255));

        txtNumeroCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaDestinoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("destinatario");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout panCuentaDestinoLayout = new javax.swing.GroupLayout(panCuentaDestino);
        panCuentaDestino.setLayout(panCuentaDestinoLayout);
        panCuentaDestinoLayout.setHorizontalGroup(
            panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                .addGroup(panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblNumeroCuentaDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70)))
                .addComponent(lblSaldoCuentaOrigen1)
                .addGap(64, 64, 64))
            .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCuentaDestino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCuentaDestinoLayout.setVerticalGroup(
            panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCuentaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoCuentaOrigen1)
                    .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                        .addGroup(panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroCuentaDestino)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panMontoTransferencia.setBackground(new java.awt.Color(12, 140, 233));
        panMontoTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaDestino1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaDestino1.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaDestino1.setText("Monto");

        lblSaldoCuentaOrigen2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoCuentaOrigen2.setForeground(new java.awt.Color(255, 255, 255));

        txtMonto.setToolTipText("");
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMontoTransferenciaLayout = new javax.swing.GroupLayout(panMontoTransferencia);
        panMontoTransferencia.setLayout(panMontoTransferenciaLayout);
        panMontoTransferenciaLayout.setHorizontalGroup(
            panMontoTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblSaldoCuentaOrigen2)
                .addGap(64, 64, 64))
            .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCuentaDestino1)
                .addContainerGap(706, Short.MAX_VALUE))
        );
        panMontoTransferenciaLayout.setVerticalGroup(
            panMontoTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCuentaDestino1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoCuentaOrigen2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnContinuarTransferencia.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnContinuarTransferencia.setText("Continuar");
        btnContinuarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panCuentaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panCuentaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panMontoTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(48, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTrasnferirTitulo)
                                .addGap(339, 339, 339))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrasnferirTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panMontoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnContinuarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panCuentaOrigen.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestino.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestino.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerCuentasActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

    private void cboCuentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuentasClienteActionPerformed
        Cuenta cuentaSeleccionada =
              (Cuenta) cboCuentasCliente.getSelectedItem();

        if (cuentaSeleccionada != null) {
            lblSaldoDisponible.setText("$ " + cuentaSeleccionada.getSaldo()
            );
        }  
    }//GEN-LAST:event_cboCuentasClienteActionPerformed

    private void txtNumeroCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaDestinoActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusGained
        if(txtMonto.getText().equals("Monto                                                                                                                                                                                                              $")){
            txtMonto.setText("");
            txtMonto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtMontoFocusGained

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
       if(txtMonto.getText().isEmpty()){
           txtMonto.setText("Monto                                                                                                                                                                                                              $");
           txtMonto.setForeground(Color.GRAY);
       }
    }//GEN-LAST:event_txtMontoFocusLost

    private void btnContinuarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarTransferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarTransferenciaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnContinuarTransferencia;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVerCuentas;
    private javax.swing.JComboBox<Cuenta> cboCuentasCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaDestino1;
    private javax.swing.JLabel lblCuentaOrigen1;
    private javax.swing.JLabel lblEstadoCuentaOrigen;
    private javax.swing.JLabel lblNumeroCuentaDestino;
    private javax.swing.JLabel lblNumeroCuentaOrigen;
    private javax.swing.JLabel lblSaldoCuentaOrigen;
    private javax.swing.JLabel lblSaldoCuentaOrigen1;
    private javax.swing.JLabel lblSaldoCuentaOrigen2;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblTrasnferirTitulo;
    private javax.swing.JPanel panCuentaDestino;
    private javax.swing.JPanel panCuentaOrigen;
    private javax.swing.JPanel panMenuBar;
    private javax.swing.JPanel panMontoTransferencia;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuentaDestino;
    // End of variables declaration//GEN-END:variables
}
