
package org.itson.proyecto01.presentacion;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import org.itson.proyecto01.control.SesionControl;
import org.itson.proyecto01.entidades.Cliente;

/**
 *
 * @author joset
 */
public class TransferenciaExitosaForm extends javax.swing.JFrame {

    /**
     * Creates new form TransferenciaExitosa
     */
    public TransferenciaExitosaForm(LocalDateTime fechaHoraOperacion, String cuentaSeleccionada, String numeroDestino, double monto, String nombreCuentaDestino) {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logoBanco.jpg"));
        setIconImage(icon);
        this.lblNumeroCuentaOrigen.setText(cuentaSeleccionada);
        this.lblNumeroCuentaDestino.setText(numeroDestino);
        this.lblNumeroMonto.setText("$ "+monto);
        this.lblNombreDestinatario.setText(nombreCuentaDestino);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        this.lblFechaHoraOperacion.setText(fechaHoraOperacion.format(formatter));
        btnVolveralMenu.setBackground(new Color(40,167,69));
        btnVolveralMenu.setForeground(Color.WHITE);
        btnVolveralMenu.setFocusPainted(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblTransferenciaExitosa = new javax.swing.JLabel();
        lblCuentaOrigen = new javax.swing.JLabel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblnombreCuentaDestino = new javax.swing.JLabel();
        lblNumeroCuentaOrigen = new javax.swing.JLabel();
        lblNumeroCuentaDestino = new javax.swing.JLabel();
        lblNumeroMonto = new javax.swing.JLabel();
        lblFechaHoraOperacion = new javax.swing.JLabel();
        lblOperacionExitosa = new javax.swing.JLabel();
        btnVolveralMenu = new javax.swing.JButton();
        lblFechaHora = new javax.swing.JLabel();
        lblNombreDestinatario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket Transferencia");

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 220, 220), 2, true));

        lblTransferenciaExitosa.setText("TRANSFERENCIA EXITOSA");

        lblCuentaOrigen.setText("Cuenta origen:");

        lblCuentaDestino.setText("Cuenta destino:");

        lblMonto.setText("Monto:");

        lblnombreCuentaDestino.setText("Destinatario");

        lblOperacionExitosa.setText("✔ Operación exitosa");

        btnVolveralMenu.setText("Volver al menu principal");
        btnVolveralMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolveralMenuActionPerformed(evt);
            }
        });

        lblFechaHora.setText("Fecha y Hora: ");

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panPrincipalLayout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(lblTransferenciaExitosa))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCuentaDestino)
                                .addComponent(lblnombreCuentaDestino, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMonto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCuentaOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFechaHora, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblOperacionExitosa)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNumeroCuentaOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(lblNumeroCuentaDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFechaHoraOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombreDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumeroMonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolveralMenu)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTransferenciaExitosa)
                .addGap(42, 42, 42)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroCuentaOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuentaOrigen))
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCuentaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumeroCuentaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroMonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto))
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblnombreCuentaDestino)
                    .addComponent(lblNombreDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaHora)
                    .addComponent(lblFechaHoraOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblOperacionExitosa)
                .addGap(38, 38, 38)
                .addComponent(btnVolveralMenu)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnVolveralMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolveralMenuActionPerformed
        Cliente cliente = new Cliente();
        cliente = SesionControl.getSesion().getCliente();
                
        MenuPrincipalForm menu = new MenuPrincipalForm();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolveralMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolveralMenu;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblFechaHoraOperacion;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreDestinatario;
    private javax.swing.JLabel lblNumeroCuentaDestino;
    private javax.swing.JLabel lblNumeroCuentaOrigen;
    private javax.swing.JLabel lblNumeroMonto;
    private javax.swing.JLabel lblOperacionExitosa;
    private javax.swing.JLabel lblTransferenciaExitosa;
    private javax.swing.JLabel lblnombreCuentaDestino;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
