package org.itson.proyecto01.presentacion;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.itson.proyecto01.entidades.Cuenta;


/**
 *
 * @author joset
 */
public class TransferenciaForm extends javax.swing.JFrame {


/**
     * Creates new form TransferenciaForm
     */
        /**
     * el metodo constructivo inicializamos el id cliente ya que todavia no
     * tenemos un login donde inice sesion el usuario
     *
     * 
     */
    public TransferenciaForm() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logoBanco.jpg"));
        setIconImage(icon);
        setLocationRelativeTo(null);

        txtMonto.setText("Monto $");
        txtMonto.setForeground(Color.GRAY);

        btnContinuarTransferencia.setForeground(Color.BLACK);
        btnContinuarTransferencia.setBorder(new javax.swing.border.LineBorder(new Color(12,140,233), 6, true));
        
        utileriasBoton(btnUsuario);
        utileriasBoton(btnCerrarSesion);
        utileriasBoton(btnConsultarOperaciones);
        utileriasBoton(btnVerCuentas);
        utileriasBoton(btnRetiroSinCuenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void utileriasBoton(JButton btn) {
        btn.setBackground(Color.WHITE);
        btn.setOpaque(true);
        btn.setContentAreaFilled(true);
        btn.setBorder(new javax.swing.border.LineBorder(new Color(12, 140, 233), 2, true));
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panMenuBar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnVerCuentas = new javax.swing.JButton();
        btnConsultarOperaciones = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        btnContinuarTransferencia = new javax.swing.JButton();
        panMontoTransferencia = new javax.swing.JPanel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblTrasnferirTitulo = new javax.swing.JLabel();
        panCuentaOrigen = new javax.swing.JPanel();
        lblNumeroCuentaOrigen = new javax.swing.JLabel();
        lblCuentaOrigen = new javax.swing.JLabel();
        cboCuentasCliente = new javax.swing.JComboBox<>();
        lblEstadoCuentaOrigen = new javax.swing.JLabel();
        lblSaldoCuentaOrigen = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        panCuentaDestino = new javax.swing.JPanel();
        lblCuentaDestino = new javax.swing.JLabel();
        lblNumeroCuentaDestino = new javax.swing.JLabel();
        lblSaldoCuentaDestino = new javax.swing.JLabel();
        txtNumeroCuentaDestino = new javax.swing.JTextField();
        lblNombreCuentaDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferencia ");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panMenuBar.setBackground(new java.awt.Color(45, 102, 237));

        btnUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");

        btnVerCuentas.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnVerCuentas.setText("Ver Cuentas");
        btnVerCuentas.setToolTipText("");
        btnVerCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuentasActionPerformed(evt);
            }
        });

        btnConsultarOperaciones.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnConsultarOperaciones.setText("<html>Consultar<br>Operaciones</html>\n");
        btnConsultarOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOperacionesActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");

        btnRetiroSinCuenta.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnRetiroSinCuenta.setText("<html>Retiro sin <br>Cuenta</html> ");
        btnRetiroSinCuenta.setToolTipText("");
        btnRetiroSinCuenta.setActionCommand("  ");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuBarLayout = new javax.swing.GroupLayout(panMenuBar);
        panMenuBar.setLayout(panMenuBarLayout);
        panMenuBarLayout.setHorizontalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRetiroSinCuenta)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCuentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarOperaciones))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panMenuBarLayout.setVerticalGroup(
            panMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnVerCuentas)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addGap(142, 142, 142))
        );

        btnContinuarTransferencia.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnContinuarTransferencia.setText("Continuar");
        btnContinuarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarTransferenciaActionPerformed(evt);
            }
        });

        panMontoTransferencia.setBackground(new java.awt.Color(45, 102, 237));
        panMontoTransferencia.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblMonto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("Monto");

        txtMonto.setToolTipText("");
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoFocusLost(evt);
            }
        });
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMontoTransferenciaLayout = new javax.swing.GroupLayout(panMontoTransferencia);
        panMontoTransferencia.setLayout(panMontoTransferenciaLayout);
        panMontoTransferenciaLayout.setHorizontalGroup(
            panMontoTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                .addGroup(panMontoTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblMonto)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panMontoTransferenciaLayout.setVerticalGroup(
            panMontoTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMontoTransferenciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lblTrasnferirTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        lblTrasnferirTitulo.setForeground(new java.awt.Color(45, 102, 237));
        lblTrasnferirTitulo.setText("Transferir");

        panCuentaOrigen.setBackground(new java.awt.Color(45, 102, 237));
        panCuentaOrigen.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblNumeroCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroCuentaOrigen.setText("Numero de cuenta");

        lblCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaOrigen.setText("CUENTA ORIGEN");

        cboCuentasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuentasClienteActionPerformed(evt);
            }
        });

        lblEstadoCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoCuentaOrigen.setText("Estado : Activa");

        lblSaldoCuentaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSaldoCuentaOrigen.setForeground(new java.awt.Color(204, 204, 204));
        lblSaldoCuentaOrigen.setText("Saldo Disponible");

        lblSaldoDisponible.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible.setText("0.00");

        javax.swing.GroupLayout panCuentaOrigenLayout = new javax.swing.GroupLayout(panCuentaOrigen);
        panCuentaOrigen.setLayout(panCuentaOrigenLayout);
        panCuentaOrigenLayout.setHorizontalGroup(
            panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstadoCuentaOrigen)
                .addContainerGap())
            .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblNumeroCuentaOrigen))
                    .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblSaldoCuentaOrigen)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
            .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblCuentaOrigen)
                    .addContainerGap(585, Short.MAX_VALUE)))
        );
        panCuentaOrigenLayout.setVerticalGroup(
            panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCuentaOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstadoCuentaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblSaldoDisponible)
                        .addGap(4, 4, 4)
                        .addComponent(lblSaldoCuentaOrigen))
                    .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                        .addComponent(lblNumeroCuentaOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(panCuentaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCuentaOrigenLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblCuentaOrigen)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        panCuentaDestino.setBackground(new java.awt.Color(45, 102, 237));
        panCuentaDestino.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(java.awt.Color.WHITE, 6, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));

        lblCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaDestino.setText("CUENTA DESTINO");

        lblNumeroCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroCuentaDestino.setText("Numero de cuenta");

        lblSaldoCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoCuentaDestino.setForeground(new java.awt.Color(255, 255, 255));

        txtNumeroCuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaDestinoActionPerformed(evt);
            }
        });

        lblNombreCuentaDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreCuentaDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCuentaDestino.setToolTipText("");

        javax.swing.GroupLayout panCuentaDestinoLayout = new javax.swing.GroupLayout(panCuentaDestino);
        panCuentaDestino.setLayout(panCuentaDestinoLayout);
        panCuentaDestinoLayout.setHorizontalGroup(
            panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                .addGroup(panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblNumeroCuentaDestino))
                    .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(lblSaldoCuentaDestino)
                .addGap(64, 64, 64))
            .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCuentaDestino)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        panCuentaDestinoLayout.setVerticalGroup(
            panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCuentaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCuentaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoCuentaDestino)
                    .addGroup(panCuentaDestinoLayout.createSequentialGroup()
                        .addComponent(lblNumeroCuentaDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombreCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btnContinuarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(panMontoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(lblTrasnferirTitulo)))
                .addGap(0, 290, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrasnferirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panMontoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinuarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panCuentaDestino.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaOrigen.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });
        panCuentaDestino.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c.getBackground()); 
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30); 
                super.paint(g2, c);
                g2.dispose();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerCuentasActionPerformed

    private void btnConsultarOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarOperacionesActionPerformed

    private void cboCuentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuentasClienteActionPerformed

    }//GEN-LAST:event_cboCuentasClienteActionPerformed

    private void txtNumeroCuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaDestinoActionPerformed

    }//GEN-LAST:event_txtNumeroCuentaDestinoActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusGained
        if (txtMonto.getText().equals("Monto $")) {
            txtMonto.setText("");
            txtMonto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtMontoFocusGained

    private void txtMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoFocusLost
        if (txtMonto.getText().isEmpty()) {
            txtMonto.setForeground(Color.GRAY);
            txtMonto.setText("Monto $");
        }
    }//GEN-LAST:event_txtMontoFocusLost

    private void btnContinuarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarTransferenciaActionPerformed
 
    }//GEN-LAST:event_btnContinuarTransferenciaActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed
    public JButton getBtnContinuarTransferencia() {
        return btnContinuarTransferencia;
    }

    public JComboBox<Cuenta> getCboCuentasCliente() {
        return cboCuentasCliente;
    }

    public JTextField getTxtMonto() {
        return txtMonto;
    }

    public JTextField getTxtNumeroCuentaDestino() {
        return txtNumeroCuentaDestino;
    }

    public JLabel getLblNombreCuentaDestino() {
        return lblNombreCuentaDestino;
    }

    public JLabel getLblSaldoDisponible() {
        return lblSaldoDisponible;
    }
    public JButton getBtnMostrarRetiroSinCuenta() {
        return btnRetiroSinCuenta;
    }
    public JButton getBtnMostrarMenu() {
        return btnVerCuentas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarOperaciones;
    private javax.swing.JButton btnContinuarTransferencia;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVerCuentas;
    private javax.swing.JComboBox<Cuenta> cboCuentasCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblEstadoCuentaOrigen;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreCuentaDestino;
    private javax.swing.JLabel lblNumeroCuentaDestino;
    private javax.swing.JLabel lblNumeroCuentaOrigen;
    private javax.swing.JLabel lblSaldoCuentaDestino;
    private javax.swing.JLabel lblSaldoCuentaOrigen;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblTrasnferirTitulo;
    private javax.swing.JPanel panCuentaDestino;
    private javax.swing.JPanel panCuentaOrigen;
    private javax.swing.JPanel panMenuBar;
    private javax.swing.JPanel panMontoTransferencia;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuentaDestino;
    // End of variables declaration//GEN-END:variables
}
